#ifndef DEFINES_H
#define DEFINES_H

#define IN_DCF_Pin GPIO_PIN_2
#define IN_DCF_GPIO_Port GPIOB
#define OUT_LED_DISPLAY_CLK_Pin GPIO_PIN_12
#define OUT_LED_DISPLAY_CLK_GPIO_Port GPIOB
#define OUT_LED_DISPLAY_DATA_Pin GPIO_PIN_13
#define OUT_LED_DISPLAY_DATA_GPIO_Port GPIOB
#define OUT_TEST_LED_Pin GPIO_PIN_14
#define OUT_TEST_LED_GPIO_Port GPIOB

#endif /* __MAIN_H */